src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Aborted_Referral_Codes__c</fullName>
        <label>Aborted Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (DCA)</relationshipLabel>
        <relationshipName>CasesForDCA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>All_Referral_Codes__c</fullName>
        <label>All Referral Codes</label>
        <length>6000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auto_Canceled_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Canceled Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Notice_Sent_Date__c</fullName>
        <label>Default Notice Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Errored_Referral_Codes__c</fullName>
        <label>Errored Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Initial_Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initial Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UnderwriterCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLockedFromUpdatesInProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLockedFromUpdatesInProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Process_Day_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Process Day Counter</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Triggered_Referral_Codes__c</fullName>
        <label>Triggered Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Workflow_Emailing_Person_Account__c</fullName>
        <description>This field is a copy of Customer Email(Person Account) to allow email notification from workflow</description>
        <label>Workflow Emailing Person Account</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DCA)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>Aborted_Referral_Codes__c</fullName>
        <label>Aborted Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Errored_Referral_Codes__c</fullName>
        <label>Errored Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triggered_Referral_Codes__c</fullName>
        <label>Triggered Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseBuilder.cls
public class CaseBuilder {

    public class Builder{
        private Case CurrentCase;
        private Account CustomerAccount;

        private Builder(Account customer_account){
            CurrentCase = new Case();
            this.CustomerAccount = customer_account;
            setDefaultCaseValues();
        }

        private Builder(){
            CurrentCase = new Case();
        }

        private Builder(Case existing_case){
            CurrentCase = existing_case;
        }

        private void setDefaultCaseValues(){
            CurrentCase.Status = 'Open';
            CurrentCase.Origin = 'Phone';
            CurrentCase.Type = 'Problem';
            CurrentCase.OwnerId = UserInfo.getUserId();
            if(CustomerAccount != null){
                CurrentCase.AccountId = CustomerAccount.Id;
                CurrentCase.Subject = 'Case Logged for: ' + CustomerAccount.Name;
                if(CustomerAccount.PersonContactId != null){
                    CurrentCase.ContactId = CustomerAccount.PersonContactId;
                }
            }
        }

        public Builder setContact(Contact contact) {
            CurrentCase.ContactId = contact.Id;
            return this;
        }

        public Builder setReason(String reason){
            CurrentCase.Reason = reason;
            return this;
        }

        public Builder setAccountId(Id account_id){
            CurrentCase.AccountId = account_id;
            return this;
        }

        public Builder setStatus(String status){
            CurrentCase.Status = status;
            return this;
        }

        public Builder setOrigin(String origin){
            CurrentCase.Origin = origin;
            return this;
        }

        public Builder setType(String type){
            CurrentCase.Type = type;
            return this;
        }

        public Builder setSubject(String subject){
            CurrentCase.Subject = subject;
            return this;
        }

        public Builder setRecordType(String record_type_name){
            CurrentCase.RecordTypeId = RecordTypeUtility.getIdByName(record_type_name);
            return this;
        }

        public Builder setRecordTypeId(Id record_type_id){
            CurrentCase.RecordTypeId = record_type_id;
            return this;
        }

        public Builder setOwner(String owner_id){
            CurrentCase.OwnerId = owner_id;
            return this;
        }

        public Builder setDescription(String description){
            CurrentCase.Description = description;
            return this;
        }

        public Builder setIsSensitive(Boolean is_sensitive){
            CurrentCase.Is_Sensitive__c = is_sensitive;
            return this;
        }

        public Builder setPriority(String priority){
            CurrentCase.Priority = priority;
            return this;
        }

        public Builder setSubProcess(String sub_process){
            CurrentCase.Sub_Process__c = sub_process;
            return this;
        }

        public Builder setProcess(String process){
            CurrentCase.Process__c = process;
            return this;
        }

        public Builder setProcessDayCounter(Decimal days){
            CurrentCase.Process_Day_Counter__c = days;
            return this;
        }

        public Builder setLoanApplication(Loan_Application__c loan_application){
            CurrentCase.Loan_Application__c = loan_application.Id;
            CurrentCase.Loan_Application__r = loan_application;
            return this;
        }

        public Builder setInitialUnderwriter(Id user_id){
            CurrentCase.Initial_Underwriter__c = user_id;
            return this;
        }

        public Builder setTriggeredReferralCodes(String referral_codes){
            CurrentCase.Triggered_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setAbortedReferralCodes(String referral_codes){
            CurrentCase.Aborted_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setErroredReferralCodes(String referral_codes){
            CurrentCase.Errored_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setLoan(Loan__c loan){
            CurrentCase.Loan__c = loan.Id;
            CurrentCase.loan__r = loan;
            return this;
        }

        public Builder setAllReferralCodes(String referral_codes){
            CurrentCase.All_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setAutoCanceledLoan(Boolean auto_canceled_loan){
            CurrentCase.Auto_Canceled_Loan__c = auto_canceled_loan;
            return this;
        }

        public Builder setAccountEmail(String customer_email){
            CurrentCase.Workflow_Emailing_Person_Account__c = customer_email;
            return this;
        }

        public Builder setAccountDCAID(String dca_id){
            CurrentCase.AccountDCA__c = dca_id;
            return this;
        }

        public Builder setDefaultNoticeSentDate(Datetime default_Notice_Sent_Date){
            CurrentCase.Default_Notice_Sent_Date__c = default_Notice_Sent_Date;
            return this;
        }

        public Builder setIsLockedFromUpdatesInProcess(Boolean is_locked){
            CurrentCase.IsLockedFromUpdatesInProcess__c = is_locked;
            return this;
        }

        public Builder setNextReviewDate(Datetime next_review_date){
            CurrentCase.Next_Review_Date__c = next_review_date;
            return this;
        }

        public Builder save(){
            upsert CurrentCase;
            return this;
        }

        public Case getRecord(){
            return this.CurrentCase;
        }

        public List<Case> getRecordList(Integer no_of_cases){
            List<Case> case_list = new List<Case>();
            for( Integer i = 0; i < no_of_cases ;i++){
                case_list.add( this.CurrentCase.clone());
            }
            return case_list;
        }
    }

    public static Builder getBuilder(Account customer_account){
        return new Builder(customer_account);
    }

    public static Builder getBuilder(Case existing_case){
        return new Builder(existing_case);
    }

    public static Builder getBuilder(){
        return new Builder();
    }
}