src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DCA)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AccountDMC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMC</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DMC)</relationshipLabel>
        <relationshipName>LoansForDMC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Approval_State__c</fullName>
        <label>Approval State</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArrearsStartDate__c</fullName>
        <label>Arrears Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Arrears_Ratio__c</fullName>
        <label>SF Arrears Ratio</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerType__c</fullName>
        <label>CustomerType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Of_Last_Missed_Plan_Payment__c</fullName>
        <label>Date Of Last Missed Plan Payment</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Default_Reason__c</fullName>
        <label>Default Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>DebtArrangementScheme</fullName>
                    <label>Debt Arrangement Scheme</label>
                </value>
                <value>
                    <fullName>DebtReliefOrder</fullName>
                    <label>Debt Relief Order</label>
                </value>
                <value>
                    <fullName>IndividualVoluntaryArrangement</fullName>
                    <label>Individual Voluntary Arrangement</label>
                </value>
                <value>
                    <fullName>Sequestration</fullName>
                </value>
                <value>
                    <fullName>TrustDeeds</fullName>
                    <label>Trust Deeds</label>
                </value>
                <value>
                    <fullName>ZopaDefault</fullName>
                    <label>Zopa Default</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disbursal_Date__c</fullName>
        <label>Disbursal Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Insitution__c</fullName>
        <label>Insitution</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <externalId>true</externalId>
        <label>Loan_Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Loan_Servicing_Fee_Rate__c</fullName>
        <label>Loan Servicing Fee Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Usage__c</fullName>
        <label>Loan Usage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monthly_Safeguard_Fee_Rate__c</fullName>
        <label>Monthly Safeguard Fee Rate</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Original_Apr__c</fullName>
        <label>Original Apr</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Original_First_Month_Repayment_Amount__c</fullName>
        <label>Original First Month Repayment Amount</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Monthly_Repayment_Amount__c</fullName>
        <label>Original Monthly Repayment Amount</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quick_Pay_Amount__c</fullName>
        <label>Quick Pay Amount</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Requested_Amount__c</fullName>
        <label>Requested Amount</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rialto_Fee__c</fullName>
        <label>Rialto Fee</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>SF Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount_Borrowed__c</fullName>
        <label>Total Amount Borrowed</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Original_Repayable_Amount__c</fullName>
        <label>Total Original Repayable Amount</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Application</relationshipLabel>
        <relationshipName>Loan_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Loan_ID__c</fullName>
        <externalId>true</externalId>
        <label>Loan ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanDetailsViewController.cls
public with sharing class LoanDetailsViewController {
    public Boolean LazyLoadFinished {public get; private set;}
    public Id CurrentLoanId {get; set{
        CurrentLoanId = value;
        setLoanDetails(value);
        }}
    public Loan__c CurrentLoan {get; set;}
    public Loan_Application__c CurrentLoanApplication {public get; private set;}
    public ApiCommandGetLoanDetails.LoanDetails LoanDetails {public get; private set;}

    public LoanDetailsViewController() {
        LazyLoadFinished = false;
    }

    private void setLoanDetails(Id loan_id){
        CurrentLoan = [SELECT Id, Account__c,
                                Account__r.Name,
                                Loan_Id__c,
                                AccountDCA__c,
                                AccountDMC__c,
                                Arrears_Ratio__c,
                                Approval_State__c,
                                Broker__c,
                                CustomerType__c,
                                Disbursal_Date__c,
                                Insitution__c,
                                Loan_Servicing_Fee_Rate__c,
                                Loan_Usage__c,
                                Market__c,
                                Monthly_Safeguard_Fee_Rate__c,
                                Original_Apr__c,
                                Original_First_Month_Repayment_Amount__c,
                                Original_Monthly_Repayment_Amount__c,
                                Quick_Pay_Amount__c,
                                Rate__c,
                                Requested_Amount__c,
                                Default_Reason__c,
                                Rialto_Fee__c,
                                Start_Date__c,
                                State__c,
                                Term__c,
                                Total_Amount_Borrowed__c,
                                Total_Original_Repayable_Amount__c,
                                Date_Of_Last_Missed_Plan_Payment__c,
                                ArrearsStartDate__c
                                 FROM Loan__c WHERE Id =: loan_id];
        if(CurrentLoan.Account__c != null){
            List<Loan_Application__c> CurrentLoanApplications = [SELECT Id, Name FROM Loan_Application__c WHERE Customer_Account__c =: CurrentLoan.Account__c];
            if(CurrentLoanApplications.size() > 0){
                CurrentLoanApplication = CurrentLoanApplications[0];
            }
        }
    }

    public PageReference getLoanDetailsInformation() {
        if(CurrentLoan.Loan_Id__c != null){
            ApiCommandGetLoanDetails get_loan_details_command = new ApiCommandGetLoanDetails(CurrentLoan.Loan_Id__c);
            ApiCommandsFactory.getInstance().performApiCommandCallout(get_loan_details_command);
            if(get_loan_details_command.CommandSuccessful){
                LoanDetails = get_loan_details_command.getResponse();
            } else {
                MessageUtility.addErrorPageMessage(get_loan_details_command.CommandError);
            }
        }else{
            MessageUtility.addErrorPageMessage('This Loan have no UUID. Cannot perform api call');
        }
        LazyLoadFinished = true;
        return null;
    }

    public Boolean getIsZCP55IsEnabled() {
        return FeatureSwitch.getSwitch('ZCP-55').isFeatureEnabled();
    }

    public Boolean getIsZCP104IsEnabled() {
        return FeatureSwitch.getSwitch('ZCP-104').isFeatureEnabled();
    }

    public Boolean getIsZCP169IsEnabled() {
        return FeatureSwitch.getSwitch('ZCP-169').isFeatureEnabled();
    }

    public Boolean getIsZCP71IsEnabled() {
        return FeatureSwitch.getSwitch('ZCP-71').isFeatureEnabled();
    }

    public Boolean getIsDefaultReason(){
        return CurrentLoan != null && String.isNotBlank(CurrentLoan.Default_Reason__c);
    }
}