src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MemberID__c</fullName>
        <externalId>true</externalId>
        <label>MemberID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <externalId>true</externalId>
        <label>Member_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanToAccountLinker.cls
public without sharing class LoanToAccountLinker {

    private static LoanToAccountLinker Instance;

    @TestVisible private Map<String, Id> MemberIdToAccountIdMap;

    public static LoanToAccountLinker getInstance() {
        if (Instance == null) {
            Instance = new LoanToAccountLinker();
        }
        return Instance;
    }

    private LoanToAccountLinker() {
        MemberIdToAccountIdMap = new Map<String, Id>();
    }

    public void getAllAccountIdsByMemberIds(List<Loan__c> new_loans){
        Set<String> member_ids_from_loans = getAllMemberIdsFromLoans(new_loans);
        MemberIdToAccountIdMap = getAccountIdsMapByMemberIds(member_ids_from_loans);
    }

    private Set<String> getAllMemberIdsFromLoans(List<Loan__c> new_loans){
        Set<String> member_ids_from_loans = new Set<String>();
        for(Loan__c new_loan : new_loans){
            member_ids_from_loans.add(new_loan.Member_ID__c);
        }
        return member_ids_from_loans;
    }

    private Map<String, Id> getAccountIdsMapByMemberIds(Set<String> member_ids_from_loans){
        member_ids_from_loans.remove(null);
        Map<String, Id> member_id_to_account_id_map = new Map<String, Id>();
        List<Account> account_list = [SELECT Id, MemberID__c FROM Account WHERE MemberID__c IN: member_ids_from_loans];
        for(Account acc : account_list){
            member_id_to_account_id_map.put(acc.MemberID__c, acc.Id);
        }
        return member_id_to_account_id_map;
    }

    public void setAccountIdForLoan(Loan__c new_loan){
        Id account_id = MemberIdToAccountIdMap.get(new_loan.Member_ID__c);
        if(account_id != null){
            new_loan.Account__c = account_id;
        }
    }
}