src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Broker</fullName>
        <active>true</active>
        <description>Broker accounts for use with Underwriting</description>
        <label>Broker</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>APR__c</fullName>
        <label>APR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Aborted_Referral_Codes__c</fullName>
        <label>Aborted Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Application</relationshipLabel>
        <relationshipName>Loan_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Documents_Last_Updated_Date__c</fullName>
        <label>Documents Last Updated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Errored_Referral_Codes__c</fullName>
        <label>Errored Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>First_Payment__c</fullName>
        <label>First Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Application_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Application_Date__c</fullName>
        <label>Loan Application Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loan_Application_Status__c</fullName>
        <label>Loan Application Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_ID__c</fullName>
        <externalId>true</externalId>
        <label>Loan ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Day__c</fullName>
        <label>Payment Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuickPay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QuickPay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Triggered_Referral_Codes__c</fullName>
        <label>Triggered Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanApplicationBuilder.cls
public class LoanApplicationBuilder {

    public class Builder{
        private Loan_Application__c Application;

        private Builder(Account related_account){
            Application = new Loan_Application__c();
            Application.Customer_Account__c = related_account.Id;
            Application.Customer_Account__r = related_account;
        }

        private Builder(Loan_Application__c loan_application){
            Application = loan_application;
        }

        public Builder setApplicationDate(DateTime application_date){
            Application.Loan_Application_Date__c = application_date;
            return this;
        }

        public Builder setApplicationAmount(Decimal application_amount){
            Application.Loan_Application_Amount__c = application_amount;
            return this;
        }

        public Builder setApplicationStatus(String application_status){
            Application.Loan_Application_Status__c = application_status;
            return this;
        }

        public Builder setApplicationName(String loan_name) {
            Application.Name = loan_name;
            return this;
        }

        public Builder setLoanId(String loan_id){
            Application.Loan_ID__c = loan_id;
            return this;
        }

        public Builder setExpiryDate(DateTime expiry_date) {
            Application.Expiry_Date__c = expiry_date;
            return this;
        }

        public Builder setPurpose(String purpose){
            Application.Purpose__c = purpose;
            return this;
        }

        public Builder setRate(Decimal rate){
            Application.Rate__c = rate;
            return this;
        }

        public Builder setFirstPayment(Decimal first_payment){
            Application.First_Payment__c = first_payment;
            return this;
        }

        public Builder setPaymentDay(Integer payment_day){
            Application.Payment_Day__c = payment_day;
            return this;
        }

        public Builder setQuickPay(Boolean quick_pay){
            Application.QuickPay__c = quick_pay;
            return this;
        }

        public Builder setInstitution(String institution){
            Application.Institution__c = institution;
            return this;
        }

        public Builder setTerm(Integer term){
            Application.Term__c = term;
            return this;
        }

        public Builder setAPR(Decimal APR){
            Application.APR__c = APR;
            return this;
        }

        public Builder setFee(Decimal fee){
            Application.Fee__c = fee;
            return this;
        }

        public Builder setBroker(String broker){
            Application.Broker__c = broker;
            return this;
        }

        public Builder setMarket(String market){
            Application.Market__c = market;
            return this;
        }

        public Builder setTriggeredReferralCodes(String referral_codes){
            Application.Triggered_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setAbortedReferralCodes(String referral_codes){
            Application.Aborted_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setErroredReferralCodes(String referral_codes){
            Application.Errored_Referral_Codes__c = referral_codes;
            return this;
        }

        public Builder setExternalId(String external_id){
            Application.Loan_ID__c = external_id;
            return this;
        }

        public Builder setDocumentsLastUpdatedDate(Datetime last_updated){
            Application.Documents_Last_Updated_Date__c = last_updated;
            return this;
        }

        public Builder save(){
            upsert Application;
            return this;
        }

        public Loan_Application__c getRecord(){
            return Application;
        }

        public List<Loan_Application__c> getRecordList(Integer number_of_loans){
            List<Loan_Application__c> loan_list = new List<Loan_Application__c>();
            for( Integer i = 0; i < number_of_loans ;i++){
                loan_list.add( this.Application.clone());
            }
            return loan_list;
        }
    }

    public static Builder getBuilder(Account related_account){
        return new Builder(related_account);
    }

    public static Builder getBuilder(Loan_Application__c loan_application){
        return new Builder(loan_application);
    }
}