src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>DCA</fullName>
        <active>true</active>
        <label>DCA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (DCA)</relationshipLabel>
        <relationshipName>CasesForDCA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Notice_Sent_Date__c</fullName>
        <label>Default Notice Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Initial_Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Initial Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>UnderwriterCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLockedFromUpdatesInProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLockedFromUpdatesInProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <label>Next Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Process_Day_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Process Day Counter</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseBuilderTest.cls
@isTest
private class CaseBuilderTest {

    static testMethod void testEmptyGetBuilderJustInitCase(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder().getRecord();
            Test.stopTest();
            System.assertNotEquals(null, test_case);
        }
    }

    static testMethod void testBuilderSetsDefaultValuesCorrectlyWithLittleLoanAndNoAccount(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            setup_data.createLoanApplication();
            Test.startTest();
               Case test_case = CaseBuilder.getBuilder(setup_data.TestAccount).getRecord();
            Test.stopTest();
            System.assertEquals('Open', test_case.Status);
            System.assertEquals('Phone', test_case.Origin);
            System.assertEquals('Problem', test_case.Type);
            System.assertEquals(setup_data.TestAccount.Id, test_case.AccountId);
        }
    }

    static testMethod void testSaveMethodWorksOnBuilder(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder(setup_data.TestAccount).
                                       setReason('Fraud').
                                       save().
                                       getRecord();
            Test.stopTest();
            Integer quantity_of_saved_cases = [SELECT Count() FROM Case];
            System.assertEquals(1, quantity_of_saved_cases, 'Expected 1 case to have been saved, instead there were ' + quantity_of_saved_cases);
        }
    }

    static testMethod void testgetCaseList(){
        SetupDataClass setup_data = new SetupDataClass();
        Integer no_of_cases =123;
        System.runAs(setup_data.TestUser){
            Test.startTest();
                List<Case> case_list = CaseBuilder.getBuilder().getRecordList(no_of_cases);
            Test.stopTest();
            System.assertEquals(no_of_cases, case_list.size() , 'List of cases has wrong size');
        }
    }

    static testMethod void testSetLoanApplication(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            setup_data.createLoanApplication();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder().setLoanApplication(setup_data.TestLoanApp).getRecord();
            Test.stopTest();
            System.assertEquals(setup_data.TestLoanApp.Id, test_case.Loan_Application__c, 'Loan Application isn\'t set correctly');
        }
    }

    static testMethod void testSetContact(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Contact test_contact = [SELECT Id FROM Contact];

            Test.startTest();
                Case test_case = CaseBuilder.getBuilder(setup_data.TestAccount).
                                       setContact(test_contact).
                                       setReason('Fraud').
                                       save().
                                       getRecord();
            Test.stopTest();

            Case new_case = [SELECT Id, ContactId FROM Case];
            System.assertEquals(test_contact.Id, new_case.ContactId, 'Contact Id of Case should be the same as Id of Contact assigned to Case.');
        }
    }

    static testMethod void testSetIsSensitive(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();

            Test.startTest();
            Case test_case = CaseBuilder.getBuilder(setup_data.TestAccount).
                    setIsSensitive(true).
                    save().
                    getRecord();
            Test.stopTest();

            Case new_case = [SELECT Id, Is_Sensitive__c FROM Case];
            System.assertEquals(true, new_case.Is_Sensitive__c, 'Case should be set as sensitive.');
        }
    }

    static testMethod void testSetAccountIdSetsIdCorrectly(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setAccountId(setup_data.TestAccount.Id)
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT AccountId FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(setup_data.TestAccount.Id, case_created.AccountId, 'Expected case to be linked to test account id');
        }
    }

    static testMethod void testSetInitialUnderwriter(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setInitialUnderwriter(setup_data.AdminUser.Id)
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Initial_Underwriter__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(setup_data.AdminUser.Id, case_created.Initial_Underwriter__c, 'Expected case to be linked to test user id');
        }
    }

    static testMethod void testSetSubStatus(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setSubProcess('DCA')
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Sub_Process__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals('DCA', case_created.Sub_Process__c, 'Sub_Process was setted wrong');
        }
    }

    static testMethod void testSetProcess(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setProcess('Collections')
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Process__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals('Collections', case_created.Process__c, 'Process was setted wrong');
        }
    }

    static testMethod void testSetProcessDayCounter(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setProcessDayCounter(5)
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Process_Day_Counter__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(5, case_created.Process_Day_Counter__c, 'Process_Day_Counter was setted wrong');
        }
    }

    static testMethod void testSetDefaultNoticeSentDate(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Datetime test_date_time = System.now();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setDefaultNoticeSentDate(test_date_time)
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Default_Notice_Sent_Date__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(test_date_time, case_created.Default_Notice_Sent_Date__c, 'Default_Notice_Sent_Date was setted wrong');
        }
    }

    static testMethod void testSetIsLockedFromUpdatesInProcess(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
            Case test_case = CaseBuilder.getBuilder()
                    .setIsLockedFromUpdatesInProcess(true)
                    .save()
                    .getRecord();
            Test.stopTest();
            Case case_created = [SELECT IsLockedFromUpdatesInProcess__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(true, case_created.IsLockedFromUpdatesInProcess__c, 'IsLockedFromUpdatesInProcess__c was setted wrong');
        }
    }

    static testMethod void testSetAccountDCAID(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                                        .setAccountDCAID(setup_data.TestAccount.Id)
                                        .save()
                                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT AccountDCA__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(setup_data.TestAccount.Id, case_created.AccountDCA__c, 'Expected case to be linked to test DCA account');
        }
    }

    static testMethod void testSetNextReviewDate(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Datetime next_review_date = Datetime.now();
            Test.startTest();
                Case test_case = CaseBuilder.getBuilder()
                        .setNextReviewDate(next_review_date)
                        .save()
                        .getRecord();
            Test.stopTest();
            Case case_created = [SELECT Next_Review_Date__c FROM Case WHERE Id =: test_case.Id];
            System.assertEquals(next_review_date, case_created.Next_Review_Date__c, 'Next_Review_Date__c has not been set');
        }
    }

    private class SetupDataClass {
        public User TestUser;
        public User AdminUser;
        public Account TestAccount {get; set;}
        public Loan_Application__c TestLoanApp {get; set;}
        public Case TestCase {get; set;}

        public SetupDataClass(){
            TestUser = [SELECT Id FROM User WHERE LastName = 'CaseBuilderTestCASE_PREP' LIMIT 1];
            AdminUser = [SELECT Id FROM User WHERE LastName = 'CaseBuilderTestSYSADMIN' LIMIT 1];
        }

        public void createTestAccount(){
            TestAccount = AccountBuilder.getBuilder().setLastName().setRecordType(RecordTypeUtility.ACCOUNT_PERSON_ACCOUNT).save().getRecord();
        }

        public void createBasicTestCase(){
            TestCase = CaseBuilder.getBuilder(TestAccount).getRecord();
        }

        public void createLoanApplication(){
            TestLoanApp = LoanApplicationBuilder.getBuilder(TestAccount).save().getRecord();
        }
    }

    @testSetup
    static void setupTestUser() {
        UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.CASE_PREP)
                                     .setLastName('CaseBuilderTestCASE_PREP')
                                     .save();
        UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.SYSADMIN)
                                     .setLastName('CaseBuilderTestSYSADMIN')
                                     .save();
    }
}