src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Configuration__c.object
<CustomObject>
    <label>Referral Codes Configuration</label>
    <nameField>
        <label>Case Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Codes Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Configuration_Task__c.object
<CustomObject>
    <fields>
        <fullName>Case_Configuration__c</fullName>
        <label>Case Configuration</label>
        <referenceTo>Case_Configuration__c</referenceTo>
        <relationshipLabel>Case Configuration Tasks</relationshipLabel>
        <relationshipName>Case_Configuration_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Configuration Task</label>
    <nameField>
        <displayFormat>CCT-{00000}</displayFormat>
        <label>Case Configuration Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configuration Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseCodeSectionControllerTest.cls
@isTest
public class CaseCodeSectionControllerTest{

    private static final String LOAN_RC_CODES = 'RC_02;RC_03';
    private static final String CASE_CONFIGURATION_CODE_NAME = 'RC_02';
    private static final String CASE_CONFIGURATION_REASON = 'Triggered';
    private static final String CASE_CONFIGURATION_DESCRIPTION = 'Test Description';
    private static final String CASE_CONFIGURATION_TASK_SUBJECT = 'Task Subject';
    private static final String CASE_CONFIGURATION_TASK_DESCRIPTION = 'Task Description';
    private static final String CASE_CONFIGURATION_TASK_TASK_FOR = 'Underwriter';

    static testMethod void testCaseCodeSectionInitComponentAttributeAsCasePrepUser(){
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.disable('ZOPA-18');
        System.runAs(setup_data.TestUser)
        {
            setup_data.createReferralCodes();
            Test.startTest();
                setup_data.initComponent();
            Test.stopTest();
            System.assert(setup_data.ClassUnderTest.CaseCodesWithCaseConfigurationDescription.size()==0, 'List should be initialized with no elements');
        }
    }

    static testMethod void testCaseCodeSectionInitComponentAttributeCasePrepUserCanSeeRelatedCaseConfigurations(){
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.disable('ZOPA-18');
        System.runAs(setup_data.TestUser)
        {
            setup_data.createReferralCodes();
            setup_data.createLoanApplicationWithCaseCodes();
            setup_data.createCaseConfigurationWithCaseConfigurationTask();
            setup_data.createCaseWithParentLoanApplication();
            Test.startTest();
                setup_data.initComponent();
            Test.stopTest();
            System.assert(setup_data.ClassUnderTest.CaseCodesWithCaseConfigurationDescription.size()==1, 'List should have a Case Configuration');
            for(CaseCodeSectionController.CaseCodeWrapper singleWrapper : setup_data.ClassUnderTest.CaseCodesWithCaseConfigurationDescription)
            {
                System.assertEquals(CASE_CONFIGURATION_CODE_NAME, singleWrapper.CodeName, 'RC Code not set correctly');
                System.assertEquals(CASE_CONFIGURATION_REASON, singleWrapper.CodeReason, 'RC Code reason not set correctly');
                System.assertEquals(CASE_CONFIGURATION_DESCRIPTION, singleWrapper.CodeDescription, 'RC Code Description not set correctly');
            }
        }
    }

    private class SetupDataClass{
        public CaseCodeSectionController ClassUnderTest;
        public User TestUser;
        public String ReferralCodes;
        public Account LoanApplicationAccount;
        public Loan_Application__c LoanApplication;
        public Case_Configuration__c CaseConfiguration;
        public Case_Configuration_Task__c CaseConfigurationTask;
        public Case CaseWithParentLoanApplication;

        public SetupDataClass() {
            TestUser = [SELECT Id FROM User WHERE LastName = 'CaseCodeSectionController' LIMIT 1];
        }

        public void initComponent() {
            ClassUnderTest = new CaseCodeSectionController();
            ClassUnderTest.IncomingTriggeredReferralCodes = ReferralCodes;
        }

        public void createReferralCodes(){
            ReferralCodes = LOAN_RC_CODES;
        }

        public void createLoanApplicationWithCaseCodes(){
            LoanApplicationAccount = AccountBuilder.getBuilder('loan application account')
                                                    .save()
                                                    .getRecord();
            LoanApplication = LoanApplicationBuilder.getBuilder(LoanApplicationAccount)
                                                    .setApplicationName('test loan application')
                                                    .setTriggeredReferralCodes(ReferralCodes)
                                                    .save()
                                                    .getRecord();
        }

        public void createCaseConfigurationWithCaseConfigurationTask(){
            CaseConfiguration = CaseConfigurationBuilder.getBuilder()
                                                    .setName(CASE_CONFIGURATION_CODE_NAME)
                                                    .setCodeDescription(CASE_CONFIGURATION_DESCRIPTION)
                                                    .save()
                                                    .getRecord();
            CaseConfigurationTask = CaseConfigurationTaskBuilder.getBuilder(CaseConfiguration)
                                                    .setTaskSubject(CASE_CONFIGURATION_TASK_SUBJECT)
                                                    .setTaskDescription(CASE_CONFIGURATION_TASK_DESCRIPTION)
                                                    .setTaskFor(CASE_CONFIGURATION_TASK_TASK_FOR)
                                                    .save()
                                                    .getRecord();
        }

        public void createCaseWithParentLoanApplication(){
            CaseWithParentLoanApplication = CaseBuilder.getBuilder(LoanApplicationAccount).save().getRecord();
        }
    }

    @testSetup
    static void setupTestUser(){
    UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.CASE_PREP)
                                 .setFirstName('CaseCodeSectionController'+Utility.getRandomInteger())
                                 .setLastName('CaseCodeSectionController')
                                 .save();
    }
}