src/objects/Case_Configuration__c.object
<CustomObject>
    <label>Referral Codes Configuration</label>
    <nameField>
        <label>Case Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Codes Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Configuration_Task__c.object
<CustomObject>
    <fields>
        <fullName>Case_Configuration__c</fullName>
        <label>Case Configuration</label>
        <referenceTo>Case_Configuration__c</referenceTo>
        <relationshipLabel>Case Configuration Tasks</relationshipLabel>
        <relationshipName>Case_Configuration_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statuses__c</fullName>
        <label>Statuses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Errored</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <label>Task Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_for__c</fullName>
        <label>Task for</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case-Prep</fullName>
                </value>
                <value>
                    <fullName>Underwriter</fullName>
                </value>
                <value>
                    <fullName>Fraud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Configuration Task</label>
    <nameField>
        <displayFormat>CCT-{00000}</displayFormat>
        <label>Case Configuration Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configuration Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseConfigurationTaskBuilder.cls
public with sharing class CaseConfigurationTaskBuilder{

    public class Builder{
        private Case_Configuration_Task__c NewCaseConfigurationTask;
        private Case_Configuration__c ParentCaseConfiguration;

        private Builder(Case_Configuration__c parent_case_configuration)
        {
            NewCaseConfigurationTask = new Case_Configuration_Task__c();
            this.ParentCaseConfiguration = parent_case_configuration;
            setDefaultCaseConfigurationTaskValues();
        }

        private Builder()
        {
            NewCaseConfigurationTask = new Case_Configuration_Task__c();
        }

        private void setDefaultCaseConfigurationTaskValues()
        {
            if(ParentCaseConfiguration != null){
                NewCaseConfigurationTask.Case_Configuration__c = ParentCaseConfiguration.Id;
            }
        }

        public Builder setTaskSubject(String task_subject){
            NewCaseConfigurationTask.Task_Subject__c = task_subject;
            return this;
        }

        public Builder setTaskDescription(String task_description){
            NewCaseConfigurationTask.Task_Description__c = task_description;
            return this;
        }

        public Builder setTaskFor(String task_for){
            NewCaseConfigurationTask.Task_For__c = task_for;
            return this;
        }

        public Builder setStatuses(String statuses) {
            NewCaseConfigurationTask.Statuses__c = statuses;
            return this;
        }

        public Builder save(){
            upsert NewCaseConfigurationTask;
            return this;
        }

        public Case_Configuration_Task__c getRecord(){
            return this.NewCaseConfigurationTask;
        }

        public List<Case_Configuration_Task__c> getRecordList(Integer no_of_case_configuration_tasks){
            List<Case_Configuration_Task__c> case_configuration_task_list = new List<Case_Configuration_Task__c>();
            for( Integer i = 0; i < no_of_case_configuration_tasks ;i++){
                case_configuration_task_list.add( this.NewCaseConfigurationTask.clone());
            }
            return case_configuration_task_list;
        }
    }

    public static Builder getBuilder(){
        return new Builder();
    }

    public static Builder getBuilder(Case_Configuration__c parent_case_configuration){
        return new Builder(parent_case_configuration);
    }
}