src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (DCA)</relationshipLabel>
        <relationshipName>CasesForDCA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DCA)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UnassignDcaHelperTest.cls
@isTest
public class UnassignDcaHelperTest {

    static testMethod void testChangeCasesAfterUnassignDcaCollectionsProcess() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.changeCaseProcess(CaseUtility.CASE_PROCESS_COLLECTIONS);
            Test.startTest();
                UnassignDcaHelper.changeCasesAfterUnassignDca(new List<Id>{setup_data.TestLoan.Id});
            Test.stopTest();
            Integer number_of_correctly_updated_cases_from_process_builder = [SELECT COUNT() FROM Case WHERE id = :setup_data.TestCase.id AND Sub_Process__c = 'Collections' AND Status = 'Open - Need to Contact' AND AccountDCA__c = null];
            System.assertEquals(1, number_of_correctly_updated_cases_from_process_builder);
        }
    }

    static testMethod void testChangeCasesAfterUnassignDcaCollectionsProcessRecoveriesProcess() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.changeCaseProcess(CaseUtility.CASE_PROCESS_RECOVERIES);
            Test.startTest();
                UnassignDcaHelper.changeCasesAfterUnassignDca(new List<Id>{setup_data.TestLoan.Id});
            Test.stopTest();
            Integer number_of_correctly_updated_cases_from_process_builder = [SELECT COUNT() FROM Case WHERE id = :setup_data.TestCase.id AND Sub_Process__c = 'Litigation' AND Status = 'Open - Need to Contact' AND AccountDCA__c = null];
            System.assertEquals(1, number_of_correctly_updated_cases_from_process_builder);
        }
    }

    private class SetupDataClass {
        public Case TestCase;
        public Loan__c TestLoan;
        public Account TestAccount;
        public User TestUser;

        public SetupDataClass() {
            TestUser = [SELECT Id FROM User WHERE LastName = 'UnassignDcaHelperTest' LIMIT 1];
            TestAccount = [SELECT id, Name, PersonContactId FROM Account WHERE Name = 'UnassignDcaHelperTestAccount' LIMIT 1];
            createLoan();
            createCollectionsRecoveriesCase();
        }

        public void createCollectionsRecoveriesCase() {
            TestCase = CaseBuilder.getBuilder(TestAccount).setRecordType(RecordTypeUtility.CASE_COLLECTIONS_RECOVERIES).setLoan(TestLoan).save().getRecord();
        }

        public void createLoan(){
            TestLoan = LoanBuilder.getBuilder(TestAccount).setExternalId('0000-0000-0000-0001').setArrearsRatio(0).save().getRecord();
        }

        public void changeCaseProcess(String new_process){
            TestCase = CaseBuilder.getBuilder(TestCase).setProcess(new_process).save().getRecord();
        }
    }

    @testSetup
    static void createAndInsertTestUser() {
        User test_user = UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.SYSADMIN)
                                     .setLastName('UnassignDcaHelperTest')
                                     .save()
                                     .getRecord();
        System.runAs(test_user){
            AccountBuilder.getBuilder('UnassignDcaHelperTestAccount').save().getRecord();
        }
    }
}