src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Aborted_Referral_Codes__c</fullName>
        <label>Aborted Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Errored_Referral_Codes__c</fullName>
        <label>Errored Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Loan_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Application</label>
        <referenceTo>Loan_Application__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Triggered_Referral_Codes__c</fullName>
        <label>Triggered Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan_Application__c.object
<CustomObject>
    <fields>
        <fullName>Aborted_Referral_Codes__c</fullName>
        <label>Aborted Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Application</relationshipLabel>
        <relationshipName>Loan_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Errored_Referral_Codes__c</fullName>
        <label>Errored Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referral_Codes__c</fullName>
        <label>Referral Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Triggered_Referral_Codes__c</fullName>
        <label>Triggered Referral Codes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <label>Loan Reference</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SupportScriptsTest.cls
@isTest
public class SupportScriptsTest {

    static testMethod void testCreateAccountReturnIdMethodReturnsIdOfNewAccount() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.disable('ZOPA-18');
        System.runAs(setup_data.TestUser){
            Test.startTest();
                Id account_id = SupportScripts.createAccountReturnId('John');
            Test.stopTest();
            System.assertEquals(1, [SELECT Id FROM Account WHERE Id = :account_id].size(), 'Method must create one new account.');
        }
    }

    static testMethod void testCreateLoanApplicationWithCaseCodes() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.disable('ZOPA-18');
        System.runAs(setup_data.TestUser){
            setup_data.createTestAccount();
            Test.startTest();
                SupportScripts.createLoanApplicationWithCaseCodes(setup_data.TestAccount, 'Sample case codes' , 'Sample case codes', 'Sample case codes', true);
            Test.stopTest();
            setup_data.queryLoan();
            System.assertEquals('Sample case codes', setup_data.TestLoan.Triggered_Referral_Codes__c, 'Method must create new loan application with Referral_Codes__c.');
            System.assertEquals('Sample case codes', setup_data.TestLoan.Aborted_Referral_Codes__c, 'Method must create new loan application with Referral_Codes__c.');
            System.assertEquals('Sample case codes', setup_data.TestLoan.Errored_Referral_Codes__c, 'Method must create new loan application with Referral_Codes__c.');
        }
    }

    private class SetupDataClass {
        public User TestUser;
        public Account TestAccount;
        public Loan_Application__c TestLoan;

        public SetupDataClass(){
            TestUser = [SELECT Id FROM User WHERE LastName = 'SupportScriptsTest' LIMIT 1];
        }

        public void createTestAccount() {
            TestAccount = AccountBuilder.getBuilder('Test').save().getRecord();
        }

        public void queryLoan() {
            TestLoan = [SELECT Triggered_Referral_Codes__c, Aborted_Referral_Codes__c, Errored_Referral_Codes__c FROM Loan_Application__c WHERE Customer_Account__c = :TestAccount.Id];
        }
    }

    @testSetup
    static void setupTestUser() {
        UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.SYSADMIN)
                                     .setLastName('SupportScriptsTest')
                                     .save();
    }
}