src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Arrears_Ratio__c</fullName>
        <label>SF Arrears Ratio</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <externalId>true</externalId>
        <label>Loan_Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateCollectionsRecoveriesCaseTest.cls
@isTest
public class CreateCollectionsRecoveriesCaseTest {

    static testMethod void testCreateCollectionsRecoveriesCases() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {

            Test.startTest();
            CreateCollectionsRecoveriesCaseHandler.createCollectionsRecoveriesCases(setup_data.TestLoan);
            Test.stopTest();

            System.assertEquals(
                    1,
                    CreateCollectionsRecoveriesCaseHandler.listCollectionsRecoveriesCase.size(),
                    'Should add cases to listCollectionsRecoveriesCase'
            );
        }
    }

    static testMethod void testUpsertCollectionsRecoveriesCases() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            CreateCollectionsRecoveriesCaseHandler.createCollectionsRecoveriesCases(setup_data.TestLoan);

            Test.startTest();
                CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
            Test.stopTest();

            System.assertEquals(
                    1,
                    [
                            SELECT COUNT()
                            FROM Case
                            WHERE Loan__c = :setup_data.TestLoan.id
                            AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                            AND Status = :CreateCollectionsRecoveriesCaseHandler.STATUS_FOR_NEW_CASE
                            AND Process__c = :CreateCollectionsRecoveriesCaseHandler.PROCESS_FOR_NEW_CASE
                            AND Sub_Process__c = :CreateCollectionsRecoveriesCaseHandler.SUB_PROCESS_FOR_NEW_CASE
                    ],
                    'Should insert case'
            );
        }
    }

    static testMethod void testChangeCaseRelatedToLoan() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestLoan.Arrears_Ratio__c = 0.5;
            update setup_data.TestLoan;
            LoanStatusChecker.LoanIdWithClosedtStatus.add(setup_data.TestLoan.id);
            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.changeCaseRelatedToLoan(new Set<id> {setup_data.TestLoan.id});
            Test.stopTest();
            System.assertEquals('Closed Paid', CreateCollectionsRecoveriesCaseHandler.MapCollectionsRecoveriesCase.get(setup_data.TestCase.id).Status, 'Should add equal Status of cases');
            System.assert(string.valueOf(CreateCollectionsRecoveriesCaseHandler.MapCollectionsRecoveriesCase.get(setup_data.TestCase.id).OwnerId).startsWith('005'), 'Owner must be a User');
        }
    }

    static testMethod void testIsChanged() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            String value_first = 'value_first';
            String clone_value_first = value_first;
            String value_second = 'value_second';
            String value_third = 'value_third';

            Test.startTest();
               Boolean result_with_identical_value = CreateCollectionsRecoveriesCaseHandler.isChanged(value_first, clone_value_first);
               Boolean result_with_different_value = CreateCollectionsRecoveriesCaseHandler.isChanged(value_second, value_third);
            Test.stopTest();

            System.assertEquals(false, result_with_identical_value);
            System.assertEquals(true, result_with_different_value);
        }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanZeroRatio() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestLoan.Arrears_Ratio__c = 0;

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.handleArrearsRatioOnChangeOnLoan(setup_data.TestLoan);
            Test.stopTest();

            System.assertEquals(
                    true,
                    CreateCollectionsRecoveriesCaseHandler.LoanIdsWithCasesNeedToBeClosed.contains(setup_data.TestLoan.Id),
                    'Should contains Loan Id'
            );
        }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanNotZeroRatio() {
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestLoan.Arrears_Ratio__c = 0.5;

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.handleArrearsRatioOnChangeOnLoan(setup_data.TestLoan);
            Test.stopTest();

            System.assertEquals(1, CreateCollectionsRecoveriesCaseHandler.ListCollectionsRecoveriesCase.size(), 'Should create new Case');
        }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanFourRatio() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestLoan.Arrears_Ratio__c = 4;
            CreateCollectionsRecoveriesCaseHandler.LoansWithOpenCasesSetIds.add(setup_data.TestLoan.Id);

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.handleArrearsRatioOnChangeOnLoan(setup_data.TestLoan);
            Test.stopTest();

            System.assertEquals(
                    true,
                    CreateCollectionsRecoveriesCaseHandler.LoanIdsWithCasesNeedToBePreDefault.contains(setup_data.TestLoan.Id),
                    'Should contains Loan Id'
            );
            System.assertEquals(
                    true,
                    CreateCollectionsRecoveriesCaseHandler.LoansUuidForSendApi.contains(setup_data.TestLoan.Loan_id__c),
                    'Should contains Loan uuid'
            );
        }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanCreateCaseRatioFour() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestLoan.Arrears_Ratio__c = 4;

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.handleArrearsRatioOnChangeOnLoan(setup_data.TestLoan);
            Test.stopTest();

            System.assertEquals(1, CreateCollectionsRecoveriesCaseHandler.ListCollectionsRecoveriesCase.size(), 'Should create new Case');
        }
    }

    static testMethod void testUpsertCollectionsRecoveriesCasesWithRatioFour() {
            SetupDataClass setup_data = new SetupDataClass();
            System.runAs(setup_data.TestUser) {
                setup_data.TestLoan.Arrears_Ratio__c = 4;
                CreateCollectionsRecoveriesCaseHandler.createCollectionsRecoveriesCases(setup_data.TestLoan);

                Test.startTest();
                    CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
                Test.stopTest();

                System.assertEquals(
                        1,
                        [
                                SELECT COUNT()
                                FROM Case
                                WHERE Loan__c = :setup_data.TestLoan.id
                                AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                                AND Status = :CreateCollectionsRecoveriesCaseHandler.STATUS_FOR_NEW_CASE
                                AND Process__c = :CreateCollectionsRecoveriesCaseHandler.PROCESS_FOR_NEW_CASE
                                AND Sub_Process__c = 'Pre-Default'
                        ],
                        'Should insert case, with Pre-Default Sub-Process'
                );
            }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanCreateCaseRatioFourOnClosedCase() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestCase.Status = 'Closed';
            update setup_data.TestCase;
            setup_data.TestLoan.Arrears_Ratio__c = 4;
            CreateCollectionsRecoveriesCaseHandler.handleArrearsRatioOnChangeOnLoan(setup_data.TestLoan);
            CreateCollectionsRecoveriesCaseHandler.changeCaseRelatedToLoan(new Set<id> {setup_data.TestLoan.id});

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
            Test.stopTest();

            System.assertEquals(
                    0,
                    [
                            SELECT COUNT()
                            FROM Case
                            WHERE Loan__c = :setup_data.TestLoan.id
                            AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                            AND IsClosed = true
                            AND Sub_Process__c = 'Pre-Default'
                            AND Status = 'Pending'
                    ],
                    'Should not update related Case to Pre-Default Sub-Process if it Closed'
            );
        }
    }

    static testMethod void testHandleArrearsRationChangeOnLoanIfCaseOnDefault() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestCase.Sub_Process__c = 'Default';
            update setup_data.TestCase;
            setup_data.TestLoan.Arrears_Ratio__c = 4;
            CreateCollectionsRecoveriesCaseHandler.LoanIdsWithCasesNeedToBeClosed.add(setup_data.TestLoan.Id);

            Test.startTest();
               CreateCollectionsRecoveriesCaseHandler.changeCaseRelatedToLoan(new Set<Id>());
               CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
            Test.stopTest();

            System.assertEquals(
                    1,
                    [
                            SELECT COUNT()
                            FROM Case
                            WHERE Loan__c = :setup_data.TestLoan.id
                            AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                            AND IsClosed = false
                            AND Sub_Process__c = 'Default'
                    ],
                    'Should not update related Case to Closed if Sub-Process is Default'
            );
        }
    }

    static testMethod void testHandleArrearsRatioChangeOnLoanIfCaseIsNotDefaultAndRatioIsGreaterThan4() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestCase.Sub_Process__c = 'Early Arrears';
            update setup_data.TestCase;
            setup_data.TestLoan.Arrears_Ratio__c = 5;
            CreateCollectionsRecoveriesCaseHandler.LoanIdsWithCasesNeedToBePreDefault.add(setup_data.TestLoan.Id);

            Test.startTest();
                CreateCollectionsRecoveriesCaseHandler.changeCaseRelatedToLoan(new Set<Id>());
                CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
            Test.stopTest();

            System.assertEquals(
                    1,
                    [
                            SELECT COUNT()
                            FROM Case
                            WHERE Loan__c = :setup_data.TestLoan.id
                            AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                            AND IsClosed = false
                            AND Sub_Process__c = 'Pre-Default'
                    ],
                    'Should update related Case to Pre-Default Sub-Process when Ratio is greater than 4 and Sub-Process is not Default.'
            );
        }
    }

    static testMethod void testHandleArrearsRatioChangeOnLoanIfCaseIsDefaultAndRatioIsGreaterThan4() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-157');
        System.runAs(setup_data.TestUser) {
            setup_data.createCollectionsRecoveriesCase();
            setup_data.TestCase.Sub_Process__c = 'Default';
            update setup_data.TestCase;
            setup_data.TestLoan.Arrears_Ratio__c = 5;
            CreateCollectionsRecoveriesCaseHandler.LoanIdsWithCasesNeedToBePreDefault.add(setup_data.TestLoan.Id);

            Test.startTest();
                CreateCollectionsRecoveriesCaseHandler.changeCaseRelatedToLoan(new Set<Id>());
                CreateCollectionsRecoveriesCaseHandler.upsertCollectionsRecoveriesCases();
            Test.stopTest();

            System.assertEquals(
                    1,
                    [
                        SELECT COUNT()
                        FROM Case
                        WHERE Loan__c = :setup_data.TestLoan.id
                        AND RecordType.Name = :CreateCollectionsRecoveriesCaseHandler.COLLECTIONS_RECOVERIES_CASE_RECORD_TYPE
                        AND IsClosed = false
                        AND Sub_Process__c = 'Default'
                    ],
                    'Should not update related Case to Pre-Default Sub-Process when Ratio is greater than 4 and Sub-Process is Default.');
        }
    }

    private class SetupDataClass {
        public User TestUser;
        public Account TestAccount;
        public Loan__c TestLoan;
        public Case TestCase;
        public SetupDataClass() {
            TestUser = [SELECT Id FROM User WHERE LastName = 'TestLastName' LIMIT 1];
            createAccount();
            createLoan();
        }

        private void createAccount() {
            TestAccount = AccountBuilder.getBuilder('TestAccountName')
                    .save()
                    .getRecord();
        }

        public void createLoan() {
            TestLoan = LoanBuilder.getBuilder(TestAccount)
                    .setExternalId('0000-0000-0000-0001')
                    .save()
                    .getRecord();
        }

        public void createCollectionsRecoveriesCase() {
            TestCase = CaseBuilder.getBuilder(TestAccount)
                    .setRecordType(RecordTypeUtility.CASE_COLLECTIONS_RECOVERIES)
                    .setLoan(TestLoan)
                    .setProcess(CaseUtility.CASE_PROCESS_COLLECTIONS)
                    .save()
                    .getRecord();
        }
    }

    @testSetup
    static void createAndInsertTestUser() {
        User test_user = UserTestData.getUserForTest()
                .setProfile(ProfileUtilities.ProfileType.SYSADMIN)
                .setLastName('TestLastName')
                .save()
                .getRecord();
    }
}