src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Arrears_Ratio__c</fullName>
        <label>SF Arrears Ratio</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <externalId>true</externalId>
        <label>Loan_Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>SF Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanStateCollectionsHelper.cls
public with sharing class LoanStateCollectionsHelper {

    @InvocableMethod(label='Change the status to Collections in ZOPA' description='Generate a request to ZOPA for change the status.')
    public static void determinateAndUpdateLoansState(List<Id> cases) {
        Map<String, String> map_loan_uuid_for_update = getListLoanUuidForUpdateState(cases);
        for (String current_uuid: map_loan_uuid_for_update.keySet()){
            changeLoanStatusToRialtoToCollectionsAuto(current_uuid,map_loan_uuid_for_update.get(current_uuid));
        }
    }

    public static Boolean changeLoanStatusToRialtoToCollections(String uuid){
        if (ApiCommandInspectorCallout.isExternalIdOfLoanCorrect(uuid)) {
            ApiCommandConfirmCollections command = new ApiCommandConfirmCollections(uuid);
            HttpResponse response = ApiCommandsFactory.getInstance().performApiCommandCallout(command);
            if (command.CommandSuccessful) {
                MessageUtility.addInfoPageMessage('Loan State was updated successfully');
                return true;
            } else {
                MessageUtility.addFatalPageMessage(command.CommandError);
            }
        }
        return false;
    }

    @future(callout=true)
    public static void changeLoanStatusToRialtoToCollectionsAuto(String uuid, String loan_id){
        if (ApiCommandInspectorCallout.isExternalIdOfLoanCorrect(uuid)) {
            ApiCommandConfirmCollections command = new ApiCommandConfirmCollections(uuid);
            HttpResponse response = ApiCommandsFactory.getInstance().performApiCommandCallout(command);
            if (command.CommandSuccessful) {
                AgentActionsRecorderForCollections recorder = AgentActionsRecorderForCollections.getInstance(AgentActionsRecorderForCollections.Action.CONFIRM_COLLECTIONS);
                recorder.record(loan_id);
                recorder.insertNewTasks();
                recorder.insertNewFeedItems();
            }
        }
    }

    @TestVisible private static Map<String, String> getListLoanUuidForUpdateState(List<Id> cases){
        Map<String, String> map_loan_uuid_for_update_state = new Map<String, String> ();
        for (Loan__c current_loan :[SELECT Loan_id__c, State__c, Arrears_Ratio__c FROM Loan__c WHERE id IN (SELECT Loan__c FROM Case WHERE id IN :cases)]){
            if (current_loan.State__c == 'withdrawn' && current_loan.Arrears_Ratio__c > 0){
                map_loan_uuid_for_update_state.put(current_loan.Loan_id__c, current_loan.id);
            }
        }
        return map_loan_uuid_for_update_state;
    }
}