src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IsLockedFromUpdatesInProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLockedFromUpdatesInProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Sub_Process__c</fullName>
        <label>Previous Sub-Process</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
                <value>
                    <fullName>Broken Repayment Arrangement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Date_Of_Last_Missed_Plan_Payment__c</fullName>
        <label>Date Of Last Missed Plan Payment</label>
        <type>DateTime</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MissedPlanPaymentHandler.cls
public with sharing class MissedPlanPaymentHandler {
    @TestVisible private static MissedPlanPaymentHandler Instance;
    @TestVisible private List<Case> CasesWithMissedPayment;
    @TestVisible private Set<Id> LoansWithMissedPayment;
    @TestVisible private AgentActionsRecorderForCollections Recorder;
    @TestVisible private Database.DMLOptions CollectionsDmlOption;
    @TestVisible private Database.DMLOptions RecoveriesDmlOption;
    @TestVisible private Database.DMLOptions SensitiveDmlOption;

    public static MissedPlanPaymentHandler getInstance() {
        if (Instance == null) {
            Instance = new MissedPlanPaymentHandler();
        }
        return Instance;
    }

    private MissedPlanPaymentHandler() {
        LoansWithMissedPayment = new Set<Id>();
        CasesWithMissedPayment = new List<Case>();
        Recorder = AgentActionsRecorderForCollections.getInstance(AgentActionsRecorderForCollections.Action.MISSED_REPAYMENT_ARRANGEMENT, null, null, false);
        CollectionsDmlOption = new Database.DMLOptions();
        CollectionsDmlOption.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance().getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_COLLECTIONS);
        RecoveriesDmlOption = new Database.DMLOptions();
        RecoveriesDmlOption.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance().getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_RECOVERIES);
        SensitiveDmlOption = new Database.DMLOptions();
        SensitiveDmlOption.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance().getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_SENSITIVE);
    }

    public void checkIsChangedDateOfLastMissedPlanPayment(Loan__c old_loan, Loan__c new_loan) {
        if (old_loan.Date_Of_Last_Missed_Plan_Payment__c != new_loan.Date_Of_Last_Missed_Plan_Payment__c) {
            LoansWithMissedPayment.add(new_loan.Id);
        }
    }

    public void updateCasesWithMissedPayments() {
        if (!LoansWithMissedPayment.isEmpty()) {
            CasesWithMissedPayment = [
                    SELECT Id, Is_Sensitive__c, Loan__c, OwnerId, Process__c, Previous_Sub_Process__c, RecordTypeId, Sub_Process__c
                    FROM Case
                    WHERE IsClosed = false
                    AND Loan__c IN :LoansWithMissedPayment
                    AND RecordTypeId = :RecordTypeUtility.getIdByName(RecordTypeUtility.CASE_COLLECTIONS_RECOVERIES)
            ];
            if (!CasesWithMissedPayment.isEmpty()) {
                for (Case case_to_update : CasesWithMissedPayment) {
                    moveCaseToBrokenArrangement(case_to_update);
                    unlockForUpdatesNotSensitiveCase(case_to_update);
                    setDmlOptions(case_to_update);
                }
                updateAllCases();
            }
            prepareRecorderRecords();
            insertRecorderRecords();
        }
    }

    private void moveCaseToBrokenArrangement(Case case_to_update) {
        case_to_update.Sub_Process__c = 'Broken Repayment Arrangement';
    }

    private void unlockForUpdatesNotSensitiveCase(Case case_to_update) {
        if (!case_to_update.Is_Sensitive__c) {
            case_to_update.IsLockedFromUpdatesInProcess__c = false;
        }
    }

    private void setDmlOptions(Case case_to_update) {
        if (case_to_update.Process__c == CaseUtility.CASE_PROCESS_COLLECTIONS) {
            case_to_update.setOptions(CollectionsDmlOption);
        } else if (case_to_update.Process__c == CaseUtility.CASE_PROCESS_RECOVERIES) {
            case_to_update.setOptions(RecoveriesDmlOption);
        } else if (case_to_update.Process__c == CaseUtility.CASE_PROCESS_SENSITIVE_CUSTOMERS) {
            case_to_update.setOptions(SensitiveDmlOption);
        }
    }

    private void updateAllCases() {
        if (CasesWithMissedPayment.size() > 0) {
            update CasesWithMissedPayment;
        }
        CasesWithMissedPayment.clear();
    }

    private void prepareRecorderRecords() {
        for (Id loan_id : LoansWithMissedPayment) {
            recorder.record(loan_id);
        }
    }

    private void insertRecorderRecords() {
        recorder.insertNewTasks();
        recorder.insertNewFeedItems();
    }
}