src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LoanSetToDefaultHandlerTest.cls
@IsTest
private class LoanSetToDefaultHandlerTest {
    static Integer BULK_SIZE = 10;

    private static testMethod void testHandleLoansSetToDefaultWhenAllLoansHaveCases() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-149');
        System.runAs(setup_data.TestUser) {
            setup_data.createTestAccountAndLoans();
            setup_data.createTestCollectionsRecoveriesCases();

            Test.startTest();
            LoanSetToDefaultHandler.handleLoansSetToDefault(setup_data.TestLoans.values());
            Test.stopTest();

            Map<Id, Case> related_cases = setup_data.queryTestCases();
            System.assertEquals(BULK_SIZE, related_cases.size(), 'Should retrieve 10 Cases.');
            for (Case case_item : related_cases.values()) {
                System.assertEquals('Recoveries', case_item.Process__c, 'Should be set to "Recoveries" process.');
                System.assertEquals('Default', case_item.Sub_Process__c, 'Should be set to "Default" sub-process.');
                System.assertEquals('Open - Need to Contact', case_item.Status, 'Should be set to "Open - Need to Contact" status.');
            }
            System.assertEquals(
                    BULK_SIZE * 2,
                    [SELECT COUNT() FROM Task WHERE (WhatId IN :setup_data.TestLoans.keySet() OR WhatId IN :related_cases.keySet())AND Type != 'Letter'],
                    'Should create 10 tasks for Cases and 10 tasks for Loans.'
            );
            System.assertEquals(
                    BULK_SIZE * 2,
                    [SELECT COUNT() FROM FeedItem WHERE ParentId IN :setup_data.TestLoans.keySet() OR ParentId IN :related_cases.keySet()],
                    'Should create 10 chatter posts for Loans and 10 chatter posts for Cases.'
            );
        }
    }

    private static testMethod void testHandleLoansSetToDefaultWhenAllLoansHaveNotCases() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.enable('ZCP-149');
        System.runAs(setup_data.TestUser) {
            setup_data.createTestAccountAndLoans();

            Test.startTest();
            LoanSetToDefaultHandler.handleLoansSetToDefault(setup_data.TestLoans.values());
            Test.stopTest();

            Map<Id, Case> related_cases = setup_data.queryTestCases();
            System.assertEquals(BULK_SIZE, related_cases.size(), 'Should retrieve 10 Cases.');
            for (Case case_item : related_cases.values()) {
                System.assertEquals('Recoveries', case_item.Process__c, 'Should be set to "Recoveries" process.');
                System.assertEquals('Default', case_item.Sub_Process__c, 'Should be set to "Default" sub-process.');
                System.assertEquals('Open - Need to Contact', case_item.Status, 'Should be set to "Open - Need to Contact" status.');
            }
            System.assertEquals(
                    BULK_SIZE * 2,
                    [SELECT COUNT() FROM Task WHERE (WhatId IN :setup_data.TestLoans.keySet() OR WhatId IN :related_cases.keySet())AND Type != 'Letter'],
                    'Should create 10 tasks for Cases and 10 tasks for Loans.'
            );
            System.assertEquals(
                    BULK_SIZE * 2,
                    [SELECT COUNT() FROM FeedItem WHERE ParentId IN :setup_data.TestLoans.keySet() OR ParentId IN :related_cases.keySet()],
                    'Should create 10 chatter posts for Loans and 10 chatter posts for Cases.'
            );
        }
    }

    private static testMethod void testHandleLoansSetToDefaultWhenZcp149IsDisabed() {
        SetupDataClass setup_data = new SetupDataClass();
        FeatureSwitch.disable('ZCP-149');
        System.runAs(setup_data.TestUser) {
            setup_data.createTestAccountAndLoans();
            setup_data.createTestCollectionsRecoveriesCases();

            Test.startTest();
            LoanSetToDefaultHandler.handleLoansSetToDefault(setup_data.TestLoans.values());
            Test.stopTest();

            Map<Id, Case> related_cases = setup_data.queryTestCases();
            System.assertEquals(BULK_SIZE, related_cases.size(), 'Should retrieve 10 Cases.');
            for (Case case_item : related_cases.values()) {
                System.assertEquals('Recoveries', case_item.Process__c, 'Should be set to "Recoveries" process.');
                System.assertEquals('Default', case_item.Sub_Process__c, 'Should be set to "Default" sub-process.');
                System.assertEquals('Open - Need to Contact', case_item.Status, 'Should be set to "Open - Need to Contact" status.');
            }
            System.assertEquals(
                    0,
            [SELECT COUNT() FROM Task WHERE (WhatId IN :setup_data.TestLoans.keySet() OR WhatId IN :related_cases.keySet())AND Type != 'Letter'],
                    'Should create 0 tasks for Cases and Loans.'
            );
            System.assertEquals(
                    0,
            [SELECT COUNT() FROM FeedItem WHERE ParentId IN :setup_data.TestLoans.keySet() OR ParentId IN :related_cases.keySet()],
                    'Should create 0 chatter posts for Loans and Cases.'
            );
        }
    }

    private class SetupDataClass {
        public User TestUser;
        public List<Account> TestAccounts;
        public Map<Id, Loan__c> TestLoans;
        public Map<Id, Case> TestCases;

        public SetupDataClass() {
            TestUser = [SELECT Id FROM User WHERE LastName = 'SYSADMIN' LIMIT 1];
        }

        public void createTestAccountAndLoans() {
            createTestAccounts();
            createTestLoans();
        }

        private void createTestAccounts() {
            TestAccounts = new List<Account>();
            for (Integer i = 0; i < BULK_SIZE; i++) {
                TestAccounts.add(createAccount('TestName' + i));
            }
            insert TestAccounts;
        }

        public Account createAccount(String name) {
            return AccountBuilder.getBuilder(name)
                    .getRecord();
        }

        private void createTestLoans() {
            List<Loan__c> new_loans = new List<Loan__c>();
            for (Integer i = 0; i < BULK_SIZE; i++) {
                new_loans.add(createLoan(TestAccounts[i], '0000-0000-0000-000' + i));
            }
            insert new_loans;
            TestLoans = new Map<Id, Loan__c>(new_loans);
        }

        public Loan__c createLoan(Account account_item, String external_id) {
            return LoanBuilder.getBuilder(account_item)
                    .setExternalId(external_id)
                    .getRecord();
        }

        public void createTestCollectionsRecoveriesCases() {
            List<Case> new_cases = new List<Case>();
            for (Loan__c loan : TestLoans.values()) {
                new_cases.add(createCollectionsRecoveriesCase(loan));
            }
            insert new_cases;
            TestCases = new Map<Id, Case>(new_cases);
        }

        public Case createCollectionsRecoveriesCase(Loan__c loan) {
            return CaseBuilder.getBuilder(loan.Account__r)
                    .setRecordType(RecordTypeUtility.CASE_COLLECTIONS_RECOVERIES)
                    .setLoan(loan)
                    .getRecord();
        }

        public Map<Id, Case> queryTestCases() {
            return new Map<Id, Case>([
                    SELECT Process__c, Sub_Process__c, Status
                    FROM Case
                    WHERE Loan__c IN :TestLoans.keySet()
            ]);
        }
    }

    @testSetup
    static void setupTestUser() {
        UserTestData.getUserForTest()
                .setProfile(ProfileUtilities.ProfileType.SYSADMIN)
                .setLastName('SYSADMIN')
                .save();
    }
}