src/objects/Case_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Code_Description__c</fullName>
        <label>Code Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Referral Codes Configuration</label>
    <nameField>
        <label>Case Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Codes Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Configuration_Task__c.object
<CustomObject>
    <fields>
        <fullName>Case_Configuration__c</fullName>
        <label>Case Configuration</label>
        <referenceTo>Case_Configuration__c</referenceTo>
        <relationshipLabel>Case Configuration Tasks</relationshipLabel>
        <relationshipName>Case_Configuration_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statuses__c</fullName>
        <label>Statuses</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Triggered</fullName>
                </value>
                <value>
                    <fullName>Errored</fullName>
                </value>
                <value>
                    <fullName>Aborted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Description__c</fullName>
        <label>Task Description</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_for__c</fullName>
        <label>Task for</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case-Prep</fullName>
                </value>
                <value>
                    <fullName>Underwriter</fullName>
                </value>
                <value>
                    <fullName>Fraud</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Configuration Task</label>
    <nameField>
        <displayFormat>CCT-{00000}</displayFormat>
        <label>Case Configuration Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configuration Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReferralCodeUtility.cls
public class ReferralCodeUtility {
    public Enum Status {TRIGGERED, ABORTED, ERRORED}
    private static ReferralCodeUtility Instance;

    @testVisible private Map<String, CaseConfigurationWrapper> CaseCodesNameToRecordMap;

    public static ReferralCodeUtility getInstance() {
        if(Instance == null){
            Instance = new ReferralCodeUtility();
        }
        return Instance;
    }

    private ReferralCodeUtility() {
        CaseCodesNameToRecordMap = new Map<String, CaseConfigurationWrapper>();
        for (Case_Configuration__c configuration_with_children:
                        [SELECT Id, Name, Code_Description__c,
                        (SELECT Task_Subject__c, Task_Description__c, Task_for__c, Statuses__c, Case_Configuration__c  FROM Case_Configuration_Tasks__r)
                        FROM Case_Configuration__c ]) {
            CaseCodesNameToRecordMap.put(configuration_with_children.Name, new CaseConfigurationWrapper(configuration_with_children));
        }
    }

    public List<Case_Configuration_Task__c> getConfigurationTasksForCodeWithSpecificStatus(String code_name, Status code_status) {
        if (CaseCodesNameToRecordMap.containsKey(code_name)) {
            return CaseCodesNameToRecordMap.get(code_name).getTasksForStatus(code_status);
        } else {
            return new List<Case_Configuration_Task__c>();
        }
    }

    private class CaseConfigurationWrapper {
        private String CodeName;
        private String StatusName;
        private Case_Configuration__c CaseConfigurationRecord;
        private List<Case_Configuration_Task__c> TriggeredCaseConfigurationTasks;
        private List<Case_Configuration_Task__c> AbortedCaseConfigurationTasks;
        private List<Case_Configuration_Task__c> ErroredCaseConfigurationTasks;

        public CaseConfigurationWrapper(Case_Configuration__c configuration_record) {
            CodeName = configuration_record.Name;
            CaseConfigurationRecord = configuration_record;
            fillConfigurationTaskLists();
        }

        private void fillConfigurationTaskLists() {
            TriggeredCaseConfigurationTasks = new List<Case_Configuration_Task__c>();
            AbortedCaseConfigurationTasks = new List<Case_Configuration_Task__c>();
            ErroredCaseConfigurationTasks = new List<Case_Configuration_Task__c>();
            for (Case_Configuration_Task__c configuration_task: CaseConfigurationRecord.Case_Configuration_Tasks__r) {
                if (configuration_task.Statuses__c.contains('Triggered')) {
                    TriggeredCaseConfigurationTasks.add(configuration_task);
                }
                if (configuration_task.Statuses__c.contains('Aborted')) {
                    AbortedCaseConfigurationTasks.add(configuration_task);
                }
                if (configuration_task.Statuses__c.contains('Errored')) {
                    ErroredCaseConfigurationTasks.add(configuration_task);
                }
            }
        }

        public List<Case_Configuration_Task__c> getTasksForStatus(Status code_status) {
            if (code_status == Status.TRIGGERED) {
                return TriggeredCaseConfigurationTasks;
            } else if (code_status == Status.ABORTED) {
                return AbortedCaseConfigurationTasks;
            } else {
                return ErroredCaseConfigurationTasks;
            }
        }
    }
}