src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IsLockedFromUpdatesInProcess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLockedFromUpdatesInProcess</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is_Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan</label>
        <referenceTo>Loan__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <label>Process</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Recoveries</fullName>
                </value>
                <value>
                    <fullName>Sensitive Customers</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Process__c</fullName>
        <label>Sub-Process</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Process__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Arrears</fullName>
                </value>
                <value>
                    <fullName>Collections</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Promise to Pay</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulties</fullName>
                </value>
                <value>
                    <fullName>Debit Relief Order</fullName>
                </value>
                <value>
                    <fullName>Protected Trust Deed</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>IVA</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Mental Health</fullName>
                </value>
                <value>
                    <fullName>Vunerable Customer</fullName>
                </value>
                <value>
                    <fullName>DCA</fullName>
                </value>
                <value>
                    <fullName>Pre-Litigation</fullName>
                </value>
                <value>
                    <fullName>Litigation</fullName>
                </value>
                <value>
                    <fullName>Sensitive Case</fullName>
                </value>
                <value>
                    <fullName>Pre-Default</fullName>
                </value>
                <value>
                    <fullName>Ready for Default</fullName>
                </value>
                <value>
                    <fullName>Back From DCA</fullName>
                </value>
                <value>
                    <fullName>On-Hold</fullName>
                </value>
                <value>
                    <fullName>Need to Contact</fullName>
                </value>
                <value>
                    <fullName>Enforcement Action Commenced</fullName>
                </value>
                <value>
                    <fullName>Judgement obtained</fullName>
                </value>
                <value>
                    <fullName>Judgement requested</fullName>
                </value>
                <value>
                    <fullName>New Recoveries</fullName>
                    <default>true</default>
                    <label>New Recoveries</label>
                </value>
                <value>
                    <fullName>Arrangement Default</fullName>
                </value>
                <value>
                    <fullName>Arrangement Expired</fullName>
                </value>
                <value>
                    <fullName>Litigation Review</fullName>
                </value>
                <value>
                    <fullName>Not Suitable to be Sued</fullName>
                </value>
                <value>
                    <fullName>Broken Promise to Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseTeamsAssingmentHandler.cls
public with sharing class CaseTeamsAssingmentHandler {
    static Database.DMLOptions CollectionsDmlOptions;
    static Database.DMLOptions RecoveriesDmlOptions;
    static Database.DMLOptions SensitiveDmlOptions;
    static AgentActionsRecorderForCollections Recorder;

    @InvocableMethod(label='Reassign Case on reach Next Review Date' description='Reassign Case on reach Next Review Date.')
    public static void assignCasesToTeamsOnNextReviewDate(List<Id> case_ids) {
        Recorder = AgentActionsRecorderForCollections.getInstance(AgentActionsRecorderForCollections.Action.MISSED_PAYMENT, null, null, false);
        List<Case> cases = getCases(case_ids);
        prepareDmlOptionsForAssignmentRules();
        unlockReassignAndChangeSubProcess(cases);
        updateCases(cases);
        insertRecorderItems();
    }

    private static List<Case> getCases(List<Id> case_ids) {
        return [
                SELECT Id, Is_Sensitive__c, Loan__c, Process__c, RecordTypeId, Sub_Process__c
                FROM Case
                WHERE Id IN :case_ids
        ];
    }

    private static void prepareDmlOptionsForAssignmentRules() {
        CollectionsDmlOptions = new Database.DMLOptions();
        CollectionsDmlOptions.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance()
                .getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_COLLECTIONS);
        RecoveriesDmlOptions = new Database.DMLOptions();
        RecoveriesDmlOptions.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance()
                .getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_RECOVERIES);
        SensitiveDmlOptions = new Database.DMLOptions();
        SensitiveDmlOptions.AssignmentRuleHeader.assignmentRuleId = CaseUtility.getInstance()
                .getAssignmentRuleIdByName(CaseUtility.AssignmentRuleName.MOVE_TO_SENSITIVE);
    }

    private static void unlockReassignAndChangeSubProcess(List<Case> cases) {
        for (Case case_item : cases) {
            unlockCase(case_item);
            setCaseAssignmentRules(case_item);
            changeCaseSubProcess(case_item);
        }
    }

    private static void unlockCase(Case case_item) {
        if (!isCaseSensitive(case_item)) {
            case_item.IsLockedFromUpdatesInProcess__c = false;
        }
    }

    private static Boolean isCaseSensitive(Case case_item) {
        return case_item.Is_Sensitive__c;
    }

    private static void setCaseAssignmentRules(Case case_item) {
        if (isCaseInCollectionsProcess(case_item)) {
            case_item.setOptions(CollectionsDmlOptions);
        } else if (isCaseInRecoveriesProcess(case_item)) {
            case_item.setOptions(RecoveriesDmlOptions);
        } else if (isCaseInSensitiveCustomersProcess(case_item)) {
            case_item.setOptions(SensitiveDmlOptions);
        }
    }

    private static Boolean isCaseInCollectionsProcess(Case case_item) {
        return isCaseInSpecificProcess(case_item, CaseUtility.CASE_PROCESS_COLLECTIONS);
    }

    private static Boolean isCaseInRecoveriesProcess(Case case_item) {
        return isCaseInSpecificProcess(case_item, CaseUtility.CASE_PROCESS_RECOVERIES);
    }

    private static Boolean isCaseInSensitiveCustomersProcess(Case case_item) {
        return isCaseInSpecificProcess(case_item, CaseUtility.CASE_PROCESS_SENSITIVE_CUSTOMERS);
    }

    private static Boolean isCaseInSpecificProcess(Case case_item, String process_name) {
        return case_item.Process__c == process_name;
    }

    private static void changeCaseSubProcess(Case case_item) {
        if (isSubProcessPromiseToPay(case_item)) {
            case_item.Sub_Process__c = 'Broken Promise to Pay';
            Recorder.record(case_item);
        }
    }

    private static Boolean isSubProcessPromiseToPay(Case case_item) {
        return case_item.Sub_Process__c == 'Promise to Pay';
    }

    private static void updateCases(List<Case> cases) {
        if (!cases.isEmpty()) {
            update cases;
        }
    }

    private static void insertRecorderItems() {
        Recorder.insertNewTasks();
        Recorder.insertNewFeedItems();
    }
}