src/objects/Feature_Switch__c.object
<CustomObject>
    <description>an object that represents a feature and whether it is currently active in sandboxes and Live</description>
    <fields>
        <fullName>Demo_approved_by__c</fullName>
        <label>Demo approved by</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JIRATicket__c</fullName>
        <label>Link to JIRA Ticket</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Release_Notes__c</fullName>
        <label>Release Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Training_Notes__c</fullName>
        <label>Training Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UAT_Approved_by__c</fullName>
        <label>UAT Approved by</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>readyForQA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for QA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>readyForRelease__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready for Release</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Switch</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feature Switches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeatureSwitchTestData.cls
@isTest
public class FeatureSwitchTestData {

    public static Builder getFeatureSwitchForTest(String switch_name){
        return new Builder(switch_name);
    }

    public class Builder{
        private Feature_Switch__c Record;

        private Builder(String switch_name){
            Record = new Feature_Switch__c(
            Name = switch_name,
            readyForRelease__c = false,
            readyForQA__c = false,
            JIRATicket__c = 'https://jira.zopa.com/browse/' + switch_name
            );
        }

        public Builder save(){
            upsert record;
            return this;
        }

        public Builder setReadyForQA(Boolean value){
            Record.readyForQA__c = value;
            return this;
        }

        public Builder setReadyForRelease(Boolean value){
            Record.readyForRelease__c = value;
            return this;
        }

        public Builder setReleaseNotes(String value){
            Record.Release_Notes__c = value;
            return this;
        }

        public Builder setTrainingNotes(String value){
            Record.Training_Notes__c = value;
            return this;
        }

        public Builder setUATApprovedBy(String value){
            Record.UAT_Approved_by__c = value;
            return this;
        }

        public Builder setDemoApprovedBy(String value){
            Record.Demo_approved_by__c = value;
            return this;
        }

        public Feature_Switch__c getRecord(){
            return Record;
        }

        public List<Feature_Switch__c> getListOfRecords(Integer number_of_records){
            List<Feature_Switch__c> feature_switch_list = new List<Feature_Switch__c>();
            for(Integer i = 0; i < number_of_records; i++){
                Feature_Switch__c feature_switch_clone = Record.clone();
                feature_switch_list.add(feature_switch_clone);
            }
            return feature_switch_list;
        }
    }
}