src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DCA)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arrears_Ratio__c</fullName>
        <label>SF Arrears Ratio</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanArrearsRatioManager.cls
public with sharing class LoanArrearsRatioManager {

    public static void checkArrearsRatio(SObject old_record, SObject new_record){
        Loan__c old_loan = (Loan__c) old_record;
        Loan__c new_loan = (Loan__c) new_record;
        if(isChangedArrearsRatio(old_loan, new_loan)){
            if(new_loan.Arrears_Ratio__c >= 4){
                new_loan.AccountDca__c = null;
            }
        }
    }

    private static Boolean isChangedArrearsRatio(Loan__c old_loan, Loan__c new_loan){
        return old_loan.Arrears_Ratio__c != new_loan.Arrears_Ratio__c;
    }
}