src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>AccountDCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCA</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans (DCA)</relationshipLabel>
        <relationshipName>Loans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Borrower</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Arrears_Ratio__c</fullName>
        <label>SF Arrears Ratio</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Id__c</fullName>
        <externalId>true</externalId>
        <label>Loan_Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <externalId>true</externalId>
        <label>Member_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>SF Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LoanBuilder.cls
public class LoanBuilder {

    public class Builder{
        private Loan__c Loan;

        private Builder(Account related_account){
            Loan = new Loan__c();
            Loan.Account__c = related_account.Id;
            Loan.Account__r = related_account;
        }

        private Builder(Loan__c loan_Loan){
            Loan = loan_Loan;
        }

        public Builder setLoanStatus(String loan_status){
            Loan.State__c = loan_status;
            return this;
        }

        public Builder setExternalId(String external_id){
            Loan.Loan_Id__c = external_id;
            return this;
        }

        public Builder setArrearsRatio(Decimal ratio){
            Loan.Arrears_Ratio__c = ratio;
            return this;
        }

        public Builder setMemberID(String member_id){
            Loan.Member_ID__c = member_id;
            return this;
        }

        public Builder setAccountDCAID(String dca_id){
            Loan.AccountDCA__c = dca_id;
            return this;
        }

        public Builder save(){
            upsert Loan;
            return this;
        }

        public Loan__c getRecord(){
            return Loan;
        }

        public List<Loan__c> getRecordList(Integer number_of_loans){
            List<Loan__c> loan_list = new List<Loan__c>();
            for( Integer i = 0; i < number_of_loans ;i++){
                loan_list.add(this.Loan.clone());
            }
            return loan_list;
        }
    }

    public static Builder getBuilder(Account related_account){
        return new Builder(related_account);
    }

    public static Builder getBuilder(Loan__c loan_Loan){
        return new Builder(loan_Loan);
    }
}