src/objects/Zopa_API_Security__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Access_Token1__c</fullName>
        <label>Access_Token1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token2__c</fullName>
        <label>Access_Token2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token3__c</fullName>
        <label>Access_Token3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token4__c</fullName>
        <label>Access_Token4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_Collections1__c</fullName>
        <label>Access_Token_Collections1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_Collections2__c</fullName>
        <label>Access_Token_Collections2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_Collections3__c</fullName>
        <label>Access_Token_Collections3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_Collections4__c</fullName>
        <label>Access_Token_Collections4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Access_Token_Expiry_Date__c</fullName>
        <label>Access Token Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Zopa API Security</label>
</CustomObject>

src/classes/OAuthZopaTest.cls
@isTest
private class OAuthZopaTest {

    static testMethod void getOAuthTokenWithCustomSettingsCollections(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.updateOAuthCustomSettings(false);
            Test.startTest();
                String token = OAuthZopa.getTokenFromSettingsCollections();
            Test.stopTest();
            String expected_token = 'OiJKV1QiLCJhbGc2BsaWNhdG200YWV2iJKV1QiLCJh2';
            System.assertEquals(expected_token, token, 'Didn\'t get the OAuth expected token');
        }
    }

    static testMethod void getOAuthTokenWithCustomSettingsUnderwriting(){
        SetupDataClass setup_data = new SetupDataClass();
        System.runAs(setup_data.TestUser) {
            setup_data.updateOAuthCustomSettings(false);
            Test.startTest();
                String token = OAuthZopa.getTokenFromSettingsUnderwriting();
            Test.stopTest();
            String expected_token = 'OiJKV1QiLCJhbGcBsaWNhdG00YWViJKV1QiLCJh';
            System.assertEquals(expected_token, token, 'Didn\'t get the OAuth expected token');
        }
    }


    public class SetupDataClass{
        public User TestUser {get; private set;}

        public SetupDataClass(){
            TestUser = [SELECT Id FROM User WHERE FirstName = 'OAuthZopaTest' AND LastName = 'OAuthZopaTest' LIMIT 1];
        }

        public void updateOAuthCustomSettings(Boolean token_expired){
            Zopa_API_Security__c api_setting = TestCustomSettings.getZopaAPISecurityCS();
            api_setting.Access_Token1__c = 'OiJKV1QiLCJhbGc';
            api_setting.Access_Token2__c = 'BsaWNhdG';
            api_setting.Access_Token3__c = '00YWV';
            api_setting.Access_Token4__c = 'iJKV1QiLCJh';
            api_setting.Access_Token_Collections1__c = 'OiJKV1QiLCJhbGc2';
            api_setting.Access_Token_Collections2__c = 'BsaWNhdG2';
            api_setting.Access_Token_Collections3__c = '00YWV2';
            api_setting.Access_Token_Collections4__c = 'iJKV1QiLCJh2';
            if(token_expired){
                api_setting.Access_Token_Expiry_Date__c = DateTime.now().addSeconds(-10);
            } else {
                api_setting.Access_Token_Expiry_Date__c = DateTime.now().addSeconds(10);
            }
            TestCustomSettings.saveCustomSettings(api_setting);
        }
    }

    @testSetup static void createAndInsertTestData() {
        UserTestData.getUserForTest().setProfile(ProfileUtilities.ProfileType.CASE_PREP)
                                     .setFirstName('OAuthZopaTest')
                                     .setLastName('OAuthZopaTest')
                                     .save();
    }
}